sudo: required

language: c

git:
  depth: false

services:
  - docker
stages:
  - compile
  - test
  - deploy

before_install:
  - docker pull xiulipan/sof

install:
  - docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/rimage-build.sh -l

jobs:
  include:
    - stage: compile
      name: "BYT Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr byt
    - stage: compile
      name: "BDW Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr bdw
    - stage: compile
      name: "HSW Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr hsw
    - stage: compile
      name: "APL Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr apl
    - stage: compile
      name: "CNL Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr cnl
    - stage: compile
      name: "SUE Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr sue
    - stage: compile
      name: "ICL Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/xtensa-build-all.sh -lr icl
    - stage: compile
      name: "Host Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/host-build-all.sh -l
