sudo: required

language: c

git:
  depth: false

services:
  - docker
stages:
  - compile
  - test
  - deploy

before_install:
  - docker pull xiulipan/sof && docker tag xiulipan/sof sof
  - docker pull xiulipan/sofqemu && docker tag xiulipan/sofqemu sofqemu

install:
  - docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/rimage-build.sh -l

jobs:
  include:
    - stage: compile
      name: "BYT Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l byt
    - stage: compile
      name: "CHT Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l cht
    - stage: compile
      name: "BDW Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l bdw
    - stage: compile
      name: "HSW Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l hsw
    - stage: compile
      name: "APL Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l apl
    - stage: compile
      name: "CNL Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l cnl
    - stage: compile
      name: "SUE Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l sue
    - stage: compile
      name: "ICL Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l icl
    - stage: compile
      name: "Host Build"
      script: docker run -it -v `pwd`:/home/sof/work/sof.git --user `id -u` xiulipan/sof ./scripts/host-build-all.sh -l
    - stage: test
      name: "BYT Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l byt && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh byt
    - stage: test
      name: "CHT Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l cht && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh cht
