sudo: required

language: c

services:
  - docker

before_install:
  - docker build --build-arg UID=$(id -u) -t sof .

script:
  - docker run -it -v `pwd`:/home/sof/work/sof.git \
           -v `pwd`/../soft.git:/home/sof/work/soft.git \
	   --user `id -u` sof ./scripts/xtensa-build-all.sh -l
