# SOF west manifest
manifest:
  version: "0.13"

  defaults:
    remote: thesofproject

  remotes:
    - name: thesofproject
      url-base: https://github.com/thesofproject
    - name: github-intel
      url-base: https://github.com/intel

  projects:
    - name: rimage
      remote: thesofproject
      repo-path: rimage
      path: sof/rimage
      revision: 6b4848e25d8aaabdf6cd9d402db9a02e5c62ae56

    - name: tomlc99
      remote: thesofproject
      repo-path: tomlc99
      path: sof/rimage/tomlc99
      revision: e3a03f5ec7d8d33be705c5ce8a632d998ce9b4d1

    - name: zephyr
      remote: github-intel
      path: zephyr
      repo-path: zephyr
      revision: 9443d6b559b81e1fced3d1f5d761ab7f68b4c467
      import:
        name-whitelist:
          - hal_xtensa
          - mbedtls
          - mipi-sys-t
          - lz4
          - tinycrypt

  self:
    path: sof
    import: submanifests
