# SOF west manifest
manifest:
  version: "0.13"

  defaults:
    remote: thesofproject

  remotes:
    - name: thesofproject
      url-base: https://github.com/thesofproject

  projects:
    - name: rimage
      remote: thesofproject
      repo-path: rimage
      path: sof/rimage
      revision: 6b4848e25d8aaabdf6cd9d402db9a02e5c62ae56

    - name: tomlc99
      remote: thesofproject
      repo-path: tomlc99
      path: sof/rimage/tomlc99
      revision: e3a03f5ec7d8d33be705c5ce8a632d998ce9b4d1

    - name: zephyr
      remote: thesofproject
      path: zephyr
      repo-path: zephyr
      revision: 4cc1b29c4d5afdbfbcde0b404a88da32e7937895
      import:
        name-whitelist:
          - hal_xtensa
          - mbedtls
          - mipi-sys-t
          - lz4
          - tinycrypt

  self:
    path: sof
    import: submanifests
