---

# For the actual fuzzer see tools/oss-fuzz/README.
# also see
# https://google.github.io/oss-fuzz/getting-started/continuous-integration/
#
# Build and run fuzzer for 5s just to check that it runs properly. If it
# consistently fails in under 5s you probably did something wrong

name: IPC fuzzer compile test

# 'workflow_dispatch' allows running this workflow manually from the
# 'Actions' tab

# yamllint disable-line rule:truthy
on: [pull_request, workflow_dispatch]

jobs:
  ipc-fuzzer-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'sound-open-firmware'

      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'sound-open-firmware'
          language: c
          fuzz-seconds: 5
